apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-container-pod
  name: multi-container-pod
spec:
  containers:
  - image: nginx:latest
    name: nginx-pod
  - name: busybox-pod
    image: busybox:latest
    command: ['sh', '-c', 'while true; do date; sleep 10; done']
    
